id: PAFA40BDA
initial_creation_type: input
source_metadata:
  title: Sarvadharmāpravṛttinirdeśa
  language: zh
  volumes:
    147f5e8b20324d1a84cc7e6f0a155607:
      title: CI_§9,i
      base_file: CI_§9,i.txt
      work_id: W20E6AB12
    58719527d1844aed9fa9d442b96d4ecd:
      title: CI_§9,ii
      base_file: CI_§9,ii.txt
      work_id: W3546F884
    f086031669ed4af1a4430ed47b075090:
      title: CI_§9,iii
      base_file: CI_§9,iii.txt
      work_id: WF4C1A1A0
    1dff303b97814b4c9ac845512dabcfeb:
      title: CI_§9,iv
      base_file: CI_§9,iv.txt
      work_id: W2849D933
    79a7b5da9ec94a2ea9dbfe6a5eee7b52:
      title: CI_§9,v
      base_file: CI_§9,v.txt
      work_id: W7830D2BA
    90d9061dcf2c44da95cd958e0050ce48:
      title: 'CI_§9,vi: Conclusion'
      base_file: 'CI_§9,vi: Conclusion.txt'
      work_id: W296B7629
    2becc70dde5845deafcc03d7fb794f08:
      title: Colophon
      base_file: Colophon.txt
      work_id: W04F0C485
    17bda32fb78e45319d62c09de2fe7a3c:
      title: Title
      base_file: Title.txt
      work_id: WFF6F7599
    bac80af4e7a34b329d7d0d84f4560c59:
      title: §1
      base_file: §1.txt
      work_id: W3666D8DD
    87cd35dd00f5422b84c09cc31dafa623:
      title: §10
      base_file: §10.txt
      work_id: W14C1B5EC
    6d37de34907c4f2eb10bc553bf3cf295:
      title: §11
      base_file: §11.txt
      work_id: W9B2D997F
    f2a049d964184544b57605812d235b3f:
      title: §12
      base_file: §12.txt
      work_id: W4D9CD4AC
    fd47cab833d343dea7f94febdbfaa528:
      title: §13
      base_file: §13.txt
      work_id: WE01E2841
    80d9cb578d80412394e142dc9792db06:
      title: §2
      base_file: §2.txt
      work_id: W26B56712
    10568d3b9b324cfdb8cb98c4e09a067f:
      title: §3
      base_file: §3.txt
      work_id: W7C12CA52
    4230ea072b2040179fb0cc8a3c1d70d2:
      title: §4
      base_file: §4.txt
      work_id: WEF8C49B0
    716107a33dd144a09e835397b1e19792:
      title: §5
      base_file: §5.txt
      work_id: WF5751F1B
    6243cdc1ca6b423288a4ec13ea792ef8:
      title: §6
      base_file: §6.txt
      work_id: W44E894AA
    8458e471df644057835ea5b1da21424d:
      title: §7
      base_file: §7.txt
      work_id: W03314381
    a3adc64c26bd4581a61836cfcbaae11d:
      title: §8
      base_file: §8.txt
      work_id: WF0552659
  chapter_to_tile:
    CI: §9
created_at: '2022-03-01T21:50:55.198733'
last_modified_at: '2022-03-01T21:50:55.198742'
